import 'package:firebase_core/firebase_core.dart';
import 'package:student_mysiswa2/webpages/login_webpage.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MySiswa Admin',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: LoginWebPage(),
      debugShowCheckedModeBanner: false,
    );
  }
}